### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by maciekpaprocki** [shortlist-digital/agreable-base-theme#42]
This repo is responsible for all the slow queries and 90% of loading time.

It seems like it causing a lot of forced updates (like image sizes) directly in options and then also triggering plugins reinstall.

**Comment by ecoad** [comment]
> options and then also triggering plugins reinstall

Woah. Okay good detective work. Can you see easy code fixes or is it a fair bit of work?

**Comment by maciekpaprocki** [comment]
Fair a bit of work although parts are straight forward. 

Either way. It's not super huge issue now, it's better to wait for theme decoupling.
